### ISSUE TITLE
Flickr Original Link on Greasyfork

### ISSUE THREAD

**Issue by MSHClivingston** [freakingprime/bought_items#1]
Hey. Are you the same freakingprime from Greasyfork?
Sorry to bother you with something unrelated to Github, but could you please update the Flickr script? They just changed the way albums are displayed and the links no longer load. I've been using that script for years, it's great.
I'm only posting this here because I don't how else to contact you.

**Comment by freakingprime** [comment]
Hi, yes I'm the author. I will look into it in 1-2 days.

**Comment by freakingprime** [comment]
It's fixed in script version 5.9.

**Comment by MSHClivingston** [comment]
Thanks again for addressing this. HOWEVER. Flickr still gets stuck at "Getting original link. Please wait..." sometimes.

What browser do you use to test your script? I'm on Firefox 121. uBlock and other Tampermonkey scripts are disabled.

**Comment by freakingprime** [comment]
I use chrome latest version. I don't use firefox for flickr so I didn't test. Try refreshing the webpage and wait. Sometimes web items are not loaded in the order I prefer.
